# Site settings
author: Alexander Bispo
title: Making my Cli application
header-img: img/home-bg.png
email: alexbispo173@gmail.com
copyright_name: Alexander Bispo
description: > # this means to ignore newlines until "baseurl:"
  the Successes and Failures and shortcuts 
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Alixzandre

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
